# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-thwc-ufi001c.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-thwc-ufi003-no-modem-oc.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-thwc-ufi003-no-modem.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8916-yiming-uz801v3.dtb
